### ISSUE TITLE
Create features files

### ISSUE THREAD

**Issue by sgomez** [aulasoftwarelibre/gata-legacy#42]
Next files must be created with the next use cases:

* [x] adding_group.feature (#46)
* [x] renaming_ group (#53)

* [x] adding_idea.feature (#59)
* [x] retitling_idea.feature (#64)
* [x] redescribing_idea.feature (#65)
* [x] accepting_idea.feature (#66)
* [x] rejecting_idea.feature (#67)

* [x] registering_as_attendee.feature (#69)
* [x] unregistering_as_attendee.feature (#70)

* [x] commenting_idea.feature (#71)
